reinicias/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('notifications/check/',views.check_new_notifications,name='check_new_notifications'),
    path('notifications/',views.show_notifications,name='notifications_show'),
    path('notifications/read/',views.update_read_notifications,name='notifications_read')
]

reinicias/patients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('diary/<int:person_id>/',views.show_diary,name='patients_show_diary'),
    path('diary/<int:person_id>/create/',views.create_diary_entry,name='patients_create_diary_entry'),
    path('feelings/<int:person_id>/',views.show_feelings,name='patients_show_feelings'),
    path('<int:person_id>/tasks/',views.show_tasks_list,name='patients_show_tasks'),
    path('<int:person_id>/tasks/add/',views.add_tasks,name='patients_add_tasks'),
    path('<int:person_id>/tasks/<int:task_id>/',views.show_tasks_details,name='patients_detail_tasks'),
    path('<int:person_id>/tasks/<int:task_id>/delivery/',views.show_delivery_details,name='patients_show_delivery'),
    path('<int:person_id>/tasks/<int:task_id>/evaluate/',views.evaluate_task,name='patients_evaluate_task'),
    path('<int:person_id>/tasks/<int:task_id>/accept/',views.accept_task,name='patients_accept_task'),
    path('<int:person_id>/tasks/<int:task_id>/deny/',views.deny_task,name='patients_deny_task'),
    path('<int:person_id>/tasks/<int:task_id>/delete/',views.delete_task,name='patients_delete_task'),
]

reinicias/reinicias/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('courses/', include('courses.urls')),
    path('technics/', include('technics.urls')),
    path('patients/',include('patients.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reinicias/patients/models.py
from django.db import models
import re
from datetime import datetime, timezone

FEELINGS = (
    ('ira','Ira'),
    ('agr','Agresividad'),
    ('fru','Frustración'),
    ('mie','Miedo'),
    ('hum','Humillación'),
    ('rec','Rechazo'),
    ('ans','Ansiedad'),
    ('ale','Alegría'),
    ('euf','Euforia'),
    ('res','Respeto'),
    ('sat','Satisfacción'),
    ('tri','Tristeza'),
    ('abu','Aburrimiento'),
    ('sol','Soledad'),
    ('dep','Depresión'),
    ('cul','Culpabilidad'),
    ('ign','Ignorancia'),
    ('ver','Vergüenza')
)

TASK_STATE = (
    ('w','En espera'),
    ('c','Completada'),
    ('a','Aceptada')
)


class Diary(models.Model):
    patient = models.OneToOneField('technics.patient',on_delete=models.CASCADE,verbose_name='Paciente')

    def __str__(self) -> str:
        return f'Diario de {self.patient}'
    
    class Meta:
        verbose_name_plural = 'Diarios'


class DiaryEntry(models.Model):

    datetime = models.DateTimeField(auto_now=True,verbose_name='Fecha y hora')
    title = models.CharField(max_length=255,verbose_name='Título')
    content = models.TextField(verbose_name='Contenido')
    feeling = models.CharField(max_length=3,verbose_name='Emoción',choices=FEELINGS)

    diary = models.ForeignKey(Diary,on_delete=models.CASCADE,verbose_name='Diario')
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name_plural = 'Entradas de diarios'


class Task(models.Model):
    title = models.CharField(max_length=255,verbose_name='Título')
    description = models.TextField(verbose_name='Descripción')
    state = models.CharField(max_length=1,verbose_name='Estado',choices=TASK_STATE)
    deadline = models.DateField(verbose_name='Fecha de entrega')
    feeling = models.CharField(max_length=3,verbose_name='Emoción',choices=FEELINGS,blank=True)

    patient = models.ForeignKey('technics.patient',on_delete=models.CASCADE,verbose_name='Paciente')
    technic = models.ForeignKey('main.technic',on_delete=models.CASCADE,verbose_name='Técnico')

    def __str__(self) -> str:
        return self.title
    
    def is_deadline_surpassed(self):
        return datetime.now(timezone.utc).date() > self.deadline
    
    class Meta:
        verbose_name_plural = 'Tareas'


class Delivery(models.Model):
    text = models.TextField(verbose_name='Entrega de texto')
    datetime = models.DateTimeField(auto_now=True,verbose_name='Fecha de entrega')

    patient = models.ForeignKey('technics.patient',on_delete=models.CASCADE,verbose_name='Paciente')
    task = models.ForeignKey(Task,on_delete=models.CASCADE,verbose_name='Tarea')

    def __str__(self) -> str:
        return f'Entrega para la tarea {self.task}'
    
    class Meta:
        verbose_name_plural = 'Entregas de tareas'


class DeliveryDocument(models.Model):
    document = models.FileField(upload_to='deliveries/%Y/%m/%d',verbose_name='Documento de entrega')

    delivery = models.ForeignKey(Delivery,on_delete=models.CASCADE,verbose_name='Entrega')

    def __str__(self) -> str:
        full_name = self.document.name
        filter_route = re.sub('deliveries/\d+/\d+/\d+/','',full_name)
        filter_extension = re.sub('\.\w+','',filter_route)
        return filter_extension
    
    class Meta:
        verbose_name_plural = 'Documentos de entrega'

reinicias/patients/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import DiaryEntry, Task, Delivery, DeliveryDocument

class DiaryEntryCreationForm(forms.ModelForm):

    class Meta:
        model = DiaryEntry
        fields = ['title','content','feeling']


class TaskCreationForm(forms.ModelForm):

    deadline = forms.DateField(label='Fecha de entrega',widget=forms.DateInput(attrs={'type':'date'},format='%Y-%m-%d'))

    class Meta:
        model = Task
        fields = ['title','description','deadline']


class DeliveryCreationForm(forms.Form):
    text = forms.CharField(required=False,widget=forms.Textarea,label='Entrega de texto')
    documents = forms.FileField(required=False,widget=forms.ClearableFileInput(attrs={'multiple':True}),label='Entrega de documentos')

reinicias/patients/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from main.views import group_required
from django.http import Http404, JsonResponse
from .models import Diary, DiaryEntry, FEELINGS, Task, Delivery, DeliveryDocument
from technics.models import Patient
from django.core.paginator import Paginator
from django.db import transaction
from .forms import DiaryEntryCreationForm, TaskCreationForm, DeliveryCreationForm
from django.core.exceptions import PermissionDenied
import plotly.express as px
from datetime import datetime, timedelta, timezone
from django.db.models import Q, F, CharField, Value
from django.db.models.functions import Concat
from main.models import Technic, Notification


# Constants
ERROR_404_PERSON = 'Ese usuario no existe'
ERROR_404_TASK = 'Esa tarea no existe'
ERROR_404_DELIVERY = 'No hay entregas para esa tarea'

FEELINGS_TRANSLATION = {f:feeling for f,feeling in FEELINGS}
FEELINGS_TO_COLORS = {
    'Ira':'#ee6131',
    'Agresividad':'#ee6131',
    'Frustración':'#ee6131',
    'Miedo':'#d76ec0',
    'Humillación':'#d76ec0',
    'Rechazo':'#d76ec0',
    'Ansiedad':'#d76ec0',
    'Alegría':'#ffbb93',
    'Euforia':'#ffbb93',
    'Respeto':'#ffbb93',
    'Satisfacción':'#ffbb93',
    'Tristeza':'#09a5d4',
    'Aburrimiento':'#09a5d4',
    'Soledad':'#09a5d4',
    'Depresión':'#09a5d4',
    'Culpabilidad':'#09a5d4',
    'Ignorancia':'#09a5d4',
    'Vergüenza':'#09a5d4'
}

@require_http_methods(['GET'])
@group_required('technics','patients')
def show_diary(request,person_id):
    this_patient = Patient.objects.filter(person__pk=person_id)
    if not this_patient.exists():
        raise Http404(ERROR_404_PERSON)
    
    this_patient = this_patient.first()
    if not (request.user.has_group('technics') or request.user.is_superuser) and request.user.get_person().pk != person_id:
        raise PermissionDenied
    this_diary = Diary.objects.get(patient=this_patient)

    diary_entries = DiaryEntry.objects.filter(diary=this_diary).order_by('-datetime')
    paginator = Paginator(diary_entries,5)

    page_number = request.GET.get('page',None)
    page_obj = paginator.get_page(page_number)

    context = {
        'userGroups':request.user.groups.all(),
        'diary':this_diary,
        'entries':page_obj,
        'pages': {
            'current':int(page_obj.number),
            'has_previous':page_obj.has_previous(),
            'has_next':page_obj.has_next()
        }
    }

    return render(request,'diary/show.html',context)


@require_http_methods(['GET','POST'])
@group_required('patients')
@transaction.atomic()
def create_diary_entry(request,person_id):
    this_patient = Patient.objects.filter(person__pk=person_id)
    if not this_patient.exists():
        raise Http404(ERROR_404_PERSON)
    
    this_patient = this_patient.first()
    this_diary = Diary.objects.get(patient=this_patient)

    form = DiaryEntryCreationForm()

    if request.method == 'POST':
        form = DiaryEntryCreationForm(request.POST)

        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.diary = this_diary
            new_entry.save()

            for technic in Technic.objects.all():
                Notification.objects.create(
                    type=f'{this_patient} ha escrito una nueva entrada en su diario.',
                    user=technic.get_user()
                )

            return redirect(f'/patients/diary/{this_patient.person.pk}')
    
    context = {
        'userGroups':request.user.groups.all(),
        'form':form
    }

    return render(request,'diary/create.html',context)


@require_http_methods(['GET'])
@group_required('technics','patients')
def show_feelings(request,person_id):
    this_patient = Patient.objects.filter(person__pk=person_id)
    if not this_patient.exists():
        raise Http404(ERROR_404_PERSON)
    
    this_patient = this_patient.first()
    this_diary = Diary.objects.get(patient=this_patient)

    if not (request.user.has_group('technics') or request.user.is_superuser) and request.user.get_person().pk != person_id:
        raise PermissionDenied
    
    entries = DiaryEntry.objects.filter(diary=this_diary).annotate(
        date=F('datetime__date'),
        type=Value('Entrada de diario',output_field=CharField()),
        ).annotate(
            new_pk=Concat(F('pk'),F('type'),output_field=CharField())
        ).values('feeling','date','type','new_pk')
    tasks = Task.objects.filter(patient=this_patient).exclude(feeling='').annotate(
        date=F('deadline'),
        type=Value('Tarea',output_field=CharField())
        ).annotate(
            new_pk=Concat(F('pk'),F('type'),output_field=CharField())
        ).values('feeling','date','type','new_pk')

    history = {}
    feelings = {}

    sorted_entries = sorted(list(entries) + list(tasks),key=lambda x : x['date'],reverse=True)
    paginator = Paginator(sorted_entries,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    for e in page_obj:
        history[e.get("new_pk")] = {
            'datetime':e.get('date'),
            'feeling':e.get('feeling'),
            'feeling_display':FEELINGS_TRANSLATION[e.get('feeling')],
            'type':e.get('type'),
        }

    for e in sorted_entries:
        if e.get('date') >= (datetime.now(timezone.utc) - timedelta(days=30)).date():
            feeling = FEELINGS_TRANSLATION[e.get('feeling')]
            color = FEELINGS_TO_COLORS[feeling]
            if feeling not in feelings:
                feelings[feeling] = (1,color)
            else:
                feelings[feeling] = (feelings[feeling][0]+1,color)

    feelings_chart = create_feelings_chart(feelings)

    context = {
        'userGroups':request.user.groups.all(),
        'history':history,
        'feelingsChart':feelings_chart,
        'pages':{
            'current':int(page_obj.number),
            'has_previous':page_obj.has_previous(),
            'has_next':page_obj.has_next()
            }
    }

    return render(request,'feelings/show.html',context)



def create_feelings_chart(feelings):
    if len(feelings) == 0:
        return '<span>No hay datos suficientes</span>'

    feeling_values = sorted(feelings.items(),key=lambda x : (x[1][1],x[0]))
    problems_fig = px.pie(
        values=[feeling[1][0] for feeling in feeling_values],
        names=[feeling[0] for feeling in feeling_values],
        color_discrete_sequence=[feeling[1][1] for feeling in feeling_values],
    )

    problems_fig.update_traces(
        hoverinfo='label+value',
        hovertemplate='%{label} <br>Cantidad: %{value}',
        hoverlabel={
            'font':{'family':'OpenSans'}
        },
        textfont={
            'color':'#ffffff',
            'family':'OpenSans'
        }
    )

    problems_fig.update_layout(
        legend={
            'font':{'family':'OpenSans'}
        },
        font={
            'family':'Montserrat'
        }
    )

    return problems_fig.to_html()


@require_http_methods(['GET'])
@group_required('technics','patients')
def show_tasks_list(request,person_id):
    this_patient = Patient.objects.filter(person__pk=person_id)
    if not this_patient.exists():
        raise Http404(ERROR_404_PERSON)
    
    this_patient = this_patient.first()

    pending_tasks = Task.objects.filter(Q(state='w') | Q(state='o'),patient=this_patient).order_by('-deadline')
    sent_tasks = Task.objects.filter(state='c',patient=this_patient).order_by('-deadline')
    accepted_tasks = Task.objects.filter(state='a',patient=this_patient).order_by('-deadline')

    context = {
        'userGroups':request.user.groups.all(),
        'pendingTasks':pending_tasks,
        'sentTasks':sent_tasks,
        'acceptedTasks':accepted_tasks,
        'feelings':FEELINGS,
        'patient':this_patient
    }
    return render(request,'tasks/list.html',context)


@require_http_methods(['GET','POST'])
@group_required('technics')
@transaction.atomic()
def add_tasks(request,person_id):
    this_patient = Patient.objects.filter(person__pk=person_id)
    if not this_patient.exists():
        raise Http404(ERROR_404_PERSON)
    
    this_patient = this_patient.first()

    form = TaskCreationForm()

    if request.method == 'POST':
        form = TaskCreationForm(request.POST)

        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.state = ('w')
            new_task.patient = this_patient
            new_task.technic = Technic.objects.get(person__user=request.user)
            new_task.save()

            Notification.objects.create(
                user=this_patient.get_user(),
                type=f'Tienes una tarea nueva: {new_task}'
            )

            return redirect(f'/patients/{this_patient.get_person().pk}/tasks/')
        print(form.errors)
    context = {
        'userGroups':request.user.groups.all(),
        'form':form
    }

    return render(request,'tasks/create.html',context)


@require_http_methods(['GET','POST'])
@group_required('patients')
@transaction.atomic()
def show_tasks_details(request,person_id,task_id):
    this_patient = Patient.objects.filter(person__pk=person_id)
    this_task = Task.objects.filter(pk=task_id)
    if not this_patient.exists():
        raise Http404(ERROR_404_PERSON)
    if not this_task.exists():
        raise Http404(ERROR_404_TASK)
    
    this_patient = this_patient.first()
    this_task = this_task.first()

    form = DeliveryCreationForm()

    if request.method == 'POST':
        form = DeliveryCreationForm(request.POST,request.FILES)

        if form.is_valid(): 
            data = form.cleaned_data
            
            new_delivery = Delivery(text=data.get('text'))
            new_delivery.task = this_task
            new_delivery.patient = this_patient
            new_delivery.save()

            if request.FILES.getlist('documents',None):

reinicias/patients/templates/diary/create.html
{% extends 'layouts/base.html' %}

{% block title %}Nueva entrada{% endblock %}

{% block body %}
{% load extra_tags %}
{% include 'components/navbar.html' with userGroups=userGroups %}
<div id="id-form-container">
<div class="container">

    <div class="row">
        <h1 class="my-4 simple-title col-12">A&ntilde;adir entrada de diario</h1>
    </div>

    <div class="row">
        {% if form.errors %}
            <div class="col-12 r-form-errors">
                <ul>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <form method="post" class="container" enctype="multipart/form-data">{% csrf_token %}
            <div class="row">
                {% for field in form %}
                    <div class="col-12 mb-2">
                        <div class="w-100 r-form-tag">
                            {{field.label_tag}}
                        </div>
                        <div class="w-100 r-form-field">
                            {{field}}
                        </div>
                        <div class="w-100 r-form-errors">
                            {{field.errors}}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row justify-content-center my-3">
                <button type="submit" class="r-form-button">Crear</button>
            </div>
        </form>
    </div>

</div>
</div>
{% endblock %}

reinicias/patients/templates/diary/show.html
{% extends 'layouts/base.html' %}

{% block title %}Mi diario{% endblock %}

{% block body %}
{% load extra_tags %}
{% include 'components/navbar.html' with userGroups=userGroups %}
<div id="id-form-container">
{% include 'components/title.html' with type="patient-title" text="Mi diario" %}
    <div class="container">
        {% if request.user.get_person.pk == diary.patient.get_person.pk %}
            <div class="row">
                <div class="col-12 hstack gap-3">
                    <button id="id-new-task" class="autoevaluation-button courses-button-cyan"><a class="text-white bi bi-plus" href="create/">Nueva entrada</a></button>
                    <div class="gif-container" id="id-new-task-gif">
                        <img class="gif-icon" src="" alt="GIF Icon"></img>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="row my-4">
            <h1 class="simple-title col-12">Entradas</h1>
        </div>

        {% if entries %}
        <div class="row accordion accordion-flush" id="accordionEntries">
            {% for entry in entries %}
            <div class="col-12 accordion-item my-3">
                <h2 class="accordion-header" id="flush-heading{{entry.pk}}">
                    <button class="accordion-button collapsed hstack gap-3" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{entry.pk}}" aria-expanded="false" aria-controls="flush-collapse{{entry.pk}}">
                        <strong>{{entry.datetime|date:"d/m/Y"}}</strong><span>{{entry.title}}</span>
                    </button>
                </h2>
                <div id="flush-collapse{{entry.pk}}" class="accordion-collapse collapse course-row-content" aria-labelledby="flush-heading{{entry.pk}}" data-bs-parent="#accordionEntries">
                    <div class="py-md-4 py-2 container-fluid vstack gap-3">
                        <div>
                            {{entry.content}}
                        </div>
                        <div>
                            <strong>Emoción:&nbsp;</strong><span>{{entry.get_feeling_display}}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
            <div class="row">
                <div class="col-12">
                    <span>No hay entradas en el diario. ¡Para escribir alguna, pulsa en el botón de "Nueva entrada"!</span>
                </div>
            </div>
        {% endif %}

        {% if pages.has_previous or pages.has_next %}
        <div id="id-pagination" class="row">
            <nav aria-label="Paginación de ususarios">
                <ul class="pagination justify-content-end">
                    {% if pages.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{pages.current|add:'-1'}}">Anterior</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{pages.current|add:'-1'}}">{{pages.current|add:"-1"}}</a></li>
                    {% endif %}
                    <li class="page-item active"><a class="page-link" href="?page={{pages.current}}">{{pages.current}}</a></li>
                    {% if pages.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{pages.current|add:'1'}}">{{pages.current|add:"1"}}</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{pages.current|add:'1'}}">Siguiente</a></li>
                    {% endif %}
                </ul>
              </nav>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

{% block script %}
{% load static %}
<script>

    let patientDiv = document.querySelector('#id-new-task-gif');
    if (patientDiv) {
        let patientButton = document.querySelector('#id-new-task');
        patientDiv.querySelector('img').src = "{% static 'assets/gifs/Papelylapiz0.png' %}";
        patientButton.addEventListener('mouseover', (e) => {
            setTimeout(() => {
                patientDiv.querySelector('img').src = "{% static 'assets/gifs/Papelylapiz.gif' %}";
            }, 50);
        });
        patientButton.addEventListener('mouseleave', (e) => {
            setTimeout(() => {
                patientDiv.querySelector('img').src = "{% static 'assets/gifs/Papelylapiz0.png' %}";
            }, 50);
        });
    }

</script>
{% endblock %}