reinicias/courses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_course,name='course_list'),
    path('filter/students/',views.filter_courses_students,name='filter_students'),
    path('filter/teachers/',views.filter_courses_teachers,name='filter_teachers'),
    path('create/', views.create_course,name='create_course'),
    path('register/', views.register_student,name='register_student'),
    path('<int:course_id>/edit',views.edit_course,name='course_edit'),
    path('<int:course_id>/delete',views.delete_course,name='course_delete'),
    path('<int:course_id>/inscribe', views.inscribe_in_course,name='inscribe'),
    path('<int:course_id>/unpublish', views.unpublish_course,name='unpublish_course'),
    path('<int:course_id>/units/create/',views.create_unit,name='create_unit'),
    path('<int:course_id>/units/<int:unit_id>/edit/',views.edit_unit,name='edit_unit'),
    path('<int:course_id>/units/<int:unit_id>/delete/',views.delete_unit,name='delete_unit'),
    path('<int:course_id>/units/<int:unit_id>/resources/add/',views.add_unit_resources,name='add_unit_resources'),
    path('<int:course_id>/units/<int:unit_id>/resources/<int:resource_id>/remove',views.remove_unit_resources,name='remove_unit_resources'),
    path('<int:course_id>/',views.details_course,name='course_details'),
    path('<int:course_id>/students',views.list_course_students,name='course_students'),
    path('autoevaluations/<int:autoevaluation_id>/',views.autoevaluation_view,name='autoevaluation_show'),
    path('autoevaluations/<int:autoevaluation_id>/edit/',views.autoevaluation_edit,name='autoevaluation_edit'),
    path('autoevaluations/<int:autoevaluation_id>/questions/add/',views.autoevaluation_add_question,name='autoevaluation_add_question'),
    path('autoevaluations/<int:autoevaluation_id>/questions/<int:question_id>/delete/',views.autoevaluation_delete_question,name='autoevaluation_delete_question'),
    path('autoevaluations/<int:autoevaluation_id>/questions/<int:question_id>/edit/',views.autoevaluation_edit_question,name='autoevaluation_edit_question'),
    path('options/<int:question_option>/delete/',views.remove_question_option,name='question_remove_option'),
    path('questions/<int:question_id>/options/add/',views.add_question_option,name='question_add_option'),
    path('autoevaluations/<int:autoevaluation_id>/start/',views.autoevaluation_start,name='autoevaluation_start'),
    path('autoevaluations/<int:autoevaluation_id>/process/',views.autoevaluation_process,name='process_autoevaluation')
] 

reinicias/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('notifications/check/',views.check_new_notifications,name='check_new_notifications'),
    path('notifications/',views.show_notifications,name='notifications_show'),
    path('notifications/read/',views.update_read_notifications,name='notifications_read')
]

reinicias/reinicias/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('courses/', include('courses.urls')),
    path('technics/', include('technics.urls')),
    path('patients/',include('patients.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reinicias/patients/models.py
from django.db import models
import re
from datetime import datetime, timezone

FEELINGS = (
    ('ira','Ira'),
    ('agr','Agresividad'),
    ('fru','Frustración'),
    ('mie','Miedo'),
    ('hum','Humillación'),
    ('rec','Rechazo'),
    ('ans','Ansiedad'),
    ('ale','Alegría'),
    ('euf','Euforia'),
    ('res','Respeto'),
    ('sat','Satisfacción'),
    ('tri','Tristeza'),
    ('abu','Aburrimiento'),
    ('sol','Soledad'),
    ('dep','Depresión'),
    ('cul','Culpabilidad'),
    ('ign','Ignorancia'),
    ('ver','Vergüenza')
)

TASK_STATE = (
    ('w','En espera'),
    ('c','Completada'),
    ('a','Aceptada')
)


class Diary(models.Model):
    patient = models.OneToOneField('technics.patient',on_delete=models.CASCADE,verbose_name='Paciente')

    def __str__(self) -> str:
        return f'Diario de {self.patient}'
    
    class Meta:
        verbose_name_plural = 'Diarios'


class DiaryEntry(models.Model):

    datetime = models.DateTimeField(auto_now=True,verbose_name='Fecha y hora')
    title = models.CharField(max_length=255,verbose_name='Título')
    content = models.TextField(verbose_name='Contenido')
    feeling = models.CharField(max_length=3,verbose_name='Emoción',choices=FEELINGS)

    diary = models.ForeignKey(Diary,on_delete=models.CASCADE,verbose_name='Diario')
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name_plural = 'Entradas de diarios'


class Task(models.Model):
    title = models.CharField(max_length=255,verbose_name='Título')
    description = models.TextField(verbose_name='Descripción')
    state = models.CharField(max_length=1,verbose_name='Estado',choices=TASK_STATE)
    deadline = models.DateField(verbose_name='Fecha de entrega')
    feeling = models.CharField(max_length=3,verbose_name='Emoción',choices=FEELINGS,blank=True)

    patient = models.ForeignKey('technics.patient',on_delete=models.CASCADE,verbose_name='Paciente')
    technic = models.ForeignKey('main.technic',on_delete=models.CASCADE,verbose_name='Técnico')

    def __str__(self) -> str:
        return self.title
    
    def is_deadline_surpassed(self):
        return datetime.now(timezone.utc).date() > self.deadline
    
    class Meta:
        verbose_name_plural = 'Tareas'


class Delivery(models.Model):
    text = models.TextField(verbose_name='Entrega de texto')
    datetime = models.DateTimeField(auto_now=True,verbose_name='Fecha de entrega')

    patient = models.ForeignKey('technics.patient',on_delete=models.CASCADE,verbose_name='Paciente')
    task = models.ForeignKey(Task,on_delete=models.CASCADE,verbose_name='Tarea')

    def __str__(self) -> str:
        return f'Entrega para la tarea {self.task}'
    
    class Meta:
        verbose_name_plural = 'Entregas de tareas'


class DeliveryDocument(models.Model):
    document = models.FileField(upload_to='deliveries/%Y/%m/%d',verbose_name='Documento de entrega')

    delivery = models.ForeignKey(Delivery,on_delete=models.CASCADE,verbose_name='Entrega')

    def __str__(self) -> str:
        full_name = self.document.name
        filter_route = re.sub('deliveries/\d+/\d+/\d+/','',full_name)
        filter_extension = re.sub('\.\w+','',filter_route)
        return filter_extension
    
    class Meta:
        verbose_name_plural = 'Documentos de entrega'

reinicias/courses/views.py
from courses.models import Course, CourseUnit, CourseUnitResource, Student, Calification, CourseStatus, \
    Autoevaluation,Question,QuestionOption
from datetime import datetime, timezone
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models, transaction
from django.db.models import Count, OuterRef, Exists, F
from django.db.models.functions import Coalesce 
from django.db.models.expressions import Subquery
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from .forms import StudentRegisterForm, CourseUnitCreateForm, CourseUnitEditForm, CourseCreateForm, \
    CourseUnitResourceCreateForm, CourseEditForm, QuestionEditForm, AutoevaluationEditForm
import json
from main.models import Person, Teacher, Notification
from main.views import group_required
from django.utils import timezone as django_timezone

# CONSTANTS
ERROR_404_COURSE = 'No existe ese curso'
ERROR_404_UNIT = 'No existe ese tema'
ERROR_404_AUTOEV = 'No existe esa autoevaluación'
ERROR_404_UNIT_RESOURCE = 'No existe ese recurso'
ERROR_404_QUESTION = 'No existe esa pregunta'

# VIEWS
@require_http_methods(["POST"])
@group_required("students")
def filter_courses_students(request):
    def get_current_courses():
        return Course.objects.filter(published=True).filter(
            coursestatus__completed=False,
            coursestatus__student=this_student) \
            .annotate(
                units=Coalesce(Subquery(
                    unit_count.annotate(count=Count('pk')).values('count'),
                    output_field=models.IntegerField()
                    ),0)) \
            .order_by('-creation_date')
    
    def get_done_courses():
        return Course.objects.filter(published=True).filter(
            coursestatus__completed=True,
            coursestatus__student=this_student) \
            .annotate(
                units=Coalesce(Subquery(
                    unit_count.annotate(count=Count('pk')).values('count'),
                    output_field=models.IntegerField()
                    ),0)) \
            .order_by('-creation_date')
    
    def get_rest_of_courses():
        rest = Course.objects.filter(published=True).exclude(pk__in=current) \
            .exclude(pk__in=done) \
            .order_by('-creation_date')
        for course in rest:
            predecessors = course.preceeded_by.all()
            if predecessors is not None and not set(predecessors).issubset(set(done)):
                rest = rest.exclude(pk=course.pk)
        rest = rest.annotate(
            units=Coalesce(Subquery(
                unit_count.annotate(count=Count('pk')).values('count'),
                output_field=models.IntegerField()
                ),0))
        return rest

    current = {}
    done = {}
    rest = {}
    query = request.POST.get('query')
    this_person = Person.objects.get(user=request.user)
    this_student = Student.objects.get(person=this_person)
    unit_count = CourseUnit.objects.filter(course=OuterRef('pk')).values('course')
    if query:
        current = get_current_courses().filter(name__icontains=query)
        done = get_done_courses().filter(name__icontains=query)
        rest = get_rest_of_courses().filter(name__icontains=query)
    else:
        current = get_current_courses()
        done = get_done_courses()
        rest = get_rest_of_courses()

    return JsonResponse({
        'current':list(current.values()),
        'done':list(done.values()),
        'rest':list(rest.values())})


@require_http_methods(["POST"])
@group_required("students")
def filter_courses_teachers(request):
    def get_published_courses():
        return Course.objects.filter(published=True).annotate(
            units=Coalesce(Subquery(
                unit_count.annotate(count=Count('pk')).values('count'),
                output_field=models.IntegerField()
                ),0)).order_by('-creation_date')
    
    def get_unpublished_courses():
        return Course.objects.filter(published=False).annotate(
            units=Coalesce(Subquery(
                unit_count.annotate(count=Count('pk')).values('count'),
                output_field=models.IntegerField()
                ),0)).order_by('-creation_date')
    
    published = {}
    not_published = {}
    query = request.POST.get('query')
    unit_count = CourseUnit.objects.filter(course=OuterRef('pk')).values('course')
    if query:
        published = get_published_courses().filter(name__icontains=query)
        not_published = get_unpublished_courses().filter(name__icontains=query)
    else:
        published = get_published_courses()
        not_published = get_unpublished_courses()

    return JsonResponse({
        'published':list(published.values()),
        'not_published':list(not_published.values())
        })


@require_http_methods(["GET"])
def list_course(request):
    unit_count = CourseUnit.objects.filter(course=OuterRef('pk')).values('course')
    if request.user.is_anonymous:
        available_courses = Course.objects.filter(published=True).filter(preceeded_by__isnull=True).annotate(
            units=Coalesce(Subquery(
                unit_count.annotate(count=Count('pk')).values('count'),
                output_field=models.IntegerField()
                ),0))

        context = {
            'courses':available_courses,
            'userGroups':request.user.groups.all(),
            }
        return render(request,'courses/list_anonymous.html',context)
    elif request.user.has_group('students'):
        this_person = Person.objects.get(user=request.user)
        this_student = Student.objects.get(person=this_person)

        check_if_course_time_has_expired(this_student)

        current_courses = Course.objects.filter(published=True).filter(
            coursestatus__completed=False,
            coursestatus__student=this_student) \
            .annotate(
                units=Coalesce(Subquery(
                    unit_count.annotate(count=Count('pk')).values('count'),
                    output_field=models.IntegerField()
                    ),0)) \
            .order_by('-creation_date')
        done_courses = Course.objects.filter(published=True).filter(
            coursestatus__completed=True,
            coursestatus__student=this_student) \
            .annotate(
                units=Coalesce(Subquery(
                    unit_count.annotate(count=Count('pk')).values('count'),
                    output_field=models.IntegerField()
                    ),0)) \
            .order_by('-creation_date')

        rest_of_courses = Course.objects.filter(published=True).exclude(pk__in=current_courses) \
            .exclude(pk__in=done_courses) \
            .order_by('-creation_date')
        for course in rest_of_courses:
            predecessors = course.preceeded_by.all()
            if predecessors is not None and not set(predecessors).issubset(set(done_courses)):
                rest_of_courses = rest_of_courses.exclude(pk=course.pk)
        rest_of_courses = rest_of_courses.annotate(
            units=Coalesce(Subquery(
                unit_count.annotate(count=Count('pk')).values('count'),
                output_field=models.IntegerField()
                ),0))

        context = {
            'currentCourses':current_courses,
            'doneCourses':done_courses,
            'restOfCourses':rest_of_courses,
            'userGroups':request.user.groups.all()
        }
        return render(request,'courses/list_students.html',context)
    elif request.user.has_group('teachers'):
        published_courses = Course.objects.filter(published=True).annotate(
            units=Coalesce(Subquery(
                unit_count.annotate(count=Count('pk')).values('count'),
                output_field=models.IntegerField()
                ),0)).order_by('-creation_date')
        non_published_courses = Course.objects.filter(published=False).annotate(
            units=Coalesce(Subquery(
                unit_count.annotate(count=Count('pk')).values('count'),
                output_field=models.IntegerField()
                ),0)).order_by('-creation_date')
        
        context = {
            'publishedCourses':published_courses,
            'nonPublishedCourses':non_published_courses,
            'userGroups':request.user.groups.all(),
        }
        
        return render(request,'courses/list_teachers.html',context)


def check_if_course_time_has_expired(student):
    inscribed_courses = CourseStatus.objects.filter(student=student)
    for course in inscribed_courses:
        if course.get_remaining_days(course.courses) <= 0:
            this_course = course.courses
            autoevaluations = Autoevaluation.objects.filter(course_unit__course=this_course)
            Calification.objects.filter(student=student,autoevaluation__in=autoevaluations).delete()
            student.options_chosen.filter(question__autoevaluation__in=autoevaluations).delete()
            course.delete()

            Notification.objects.create(
                type=f'Usted no ha completado el curso {this_course} ha tiempo, se ha reestablecido su progreso.',
                user=student.get_user()
            )
            Notification.objects.create(
                type=f'{student} no ha completado el curso {this_course} ha tiempo, se ha reestablecido su progreso.',
                user=this_course.teacher.get_user()
            )


@require_http_methods(["GET","POST"])
@transaction.atomic()
def register_student(request):
    form = StudentRegisterForm()
    if request.method == "POST":
        form = StudentRegisterForm(request.POST)
        if form.is_valid():
            # Create USER
            user = form.save(commit=False)
            user.save()

reinicias/courses/templates/components/autoevaluation_options.html
<ul class="autoevaluation-options-list">
    {% for option in options %}
    <div class="form-check">
        {% if multiple %}
            <input class="form-check-input" type="checkbox" name="question-{{question.pk}}-option" value="{{option.pk}}" id="id-{{option.pk}}">
            <label class="form-check-label" for="id-{{option.pk}}">{{option.option_name}}</label>
            <br>
        {% else %}
            <input class="form-check-input" type="radio" name="question-{{question.pk}}-option" value="{{option.pk}}" id="id-{{option.pk}}">
            <label class="form-check-label" for="id-{{option.pk}}">{{option.option_name}}</label>
        {% endif %}
    </div>
    {% endfor %}
</ul>

reinicias/courses/templates/components/courserow.html
{% comment %}
IN:
- type = "seelist"/"enrol"
- course
- parent_id (accordion div)
- editable

Attributes for course:
-> name
-> description
-> units: derived
{% endcomment %}

<div class="accordion-item my-3">
    <h2 class="accordion-header" id="flush-heading{{course.pk}}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{course.pk}}" aria-expanded="false" aria-controls="flush-collapse{{course.pk}}">
            {{course.name}}
        </button>
    </h2>
    <div id="flush-collapse{{course.pk}}" class="accordion-collapse collapse course-row-content" aria-labelledby="flush-heading{{course.pk}}" data-bs-parent="#{{parent_id}}">
        <div class="py-md-4 pb-2">
            <div class="w-100">
                {{course.description}}
            </div>
            <div class="w-100">
                <span class="text-xs"><strong>Temas:&nbsp;</strong>{{course.units}}</span>
                <br>
                <span class="text-xs"><strong>Duraci&oacute;n (semanas):&nbsp;</strong>{{course.duration}}</span>
                <br>
                {% if course.index_document %}
                <span class="text-xs"><strong>Documento de curso:&nbsp;</strong><a target="_blank" href="{{MEDIA_URL}}{{course.index_document.name}}" rel="noopener">{{course.get_document_display}}</a></span>
                {% endif %}
            </div>
            <div class="w-100 d-flex">
                {% if type == "seelist" %}
                <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="{{course.pk}}/" ><span>Ver curso</span></a></button>
                {% elif type == "enrol" %}
                <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="{{course.pk}}/inscribe"><span>Inscribirse</span></a></button>
                {% endif %}
                
                {% if not student %}
                    {% if not course.published %}
                    <button class="my-3 ms-3 courses-button courses-button-cyan"><a class="text-white" href="{{course.pk}}/edit"><span>Editar</span></a></button>
                    <button class="my-3 ms-3 courses-button courses-button-cyan" type="submit"><a class="text-white" href="{{course.pk}}/delete"><span>Borrar</span></a></button>
                    {% else %}
                    <button class="my-3 ms-3 courses-button courses-button-cyan" type="submit"><a class="text-white" href="{{course.pk}}/unpublish"><span>Despublicar</span></a></button>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

reinicias/courses/templates/components/courserow2.html
{% comment %}
IN:
- type = "seelist"/"enrol"
- course
- parent_id (accordion div)
- editable

Attributes for course:
-> name
-> description
-> units: derived
{% endcomment %}

<div class="accordion-item my-3">
    <h2 class="accordion-header" id="flush-heading{{course.pk}}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{course.pk}}" aria-expanded="false" aria-controls="flush-collapse{{course.pk}}">
            {{course.name}}
        </button>
    </h2>
    <div id="flush-collapse{{course.pk}}" class="accordion-collapse collapse course-row-content" aria-labelledby="flush-heading{{course.pk}}" data-bs-parent="#{{parent_id}}">
        <div class="py-md-4 pb-2">
            <div class="w-100">
                {{course.description}}
            </div>
            <div class="w-100">
                <span><strong>Temas:&nbsp;</strong>{{course.units}}</span>
            </div>
            <div class="w-100 d-flex">
                {% if type == "seelist" %}
                <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="{{course.pk}}/" ><span>Ver curso</span></a></button>
                {% elif type == "enrol" %}
                <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="{{course.pk}}/inscribe"><span>Inscribirse</span></a></button>
                {% endif %}
                
                {% if not student %}
                    {% if not course.published %}
                    <button class="my-3 ms-3 courses-button courses-button-cyan"><a class="text-white" href="{{course.pk}}/edit"><span>Editar</span></a></button>
                    <button class="my-3 ms-3 courses-button courses-button-cyan" type="submit"><a class="text-white" href="{{course.pk}}/delete"><span>Borrar</span></a></button>
                    {% else %}
                    <button class="my-3 ms-3 courses-button courses-button-cyan" type="submit"><a class="text-white" href="{{course.pk}}/unpublish"><span>Despublicar</span></a></button>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

reinicias/courses/templates/components/courserow_anonymous.html
<div class="accordion-item my-3">
    <h2 class="accordion-header" id="flush-heading{{course.pk}}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{course.pk}}" aria-expanded="false" aria-controls="flush-collapse{{course.pk}}">
            {{course.name}}
        </button>
    </h2>
    <div id="flush-collapse{{course.pk}}" class="accordion-collapse collapse course-row-content" aria-labelledby="flush-heading{{course.pk}}" data-bs-parent="#{{parent_id}}">
        <div class="py-md-4 pb-2">
            <div class="w-100">
                {{course.description}}
            </div>
            <div class="w-100">
                <span><strong>Temas:&nbsp;</strong>{{course.units}}</span>
                <br>
                <span class="text-xs"><strong>Duraci&oacute;n (semanas):&nbsp;</strong>{{course.duration}}</span>
                <br>
                {% if course.index_document %}
                <span class="text-xs"><strong>Documento de curso:&nbsp;</strong><a target="_blank" href="{{MEDIA_URL}}{{course.index_document.name}}" rel="noopener">{{course.get_document_display}}</a></span>
                {% endif %}
            </div>
        </div>
    </div>
</div>

reinicias/courses/templates/components/coursesection.html
{% load static %}
<div class="row my-4">
    <div class="col-12 d-flex">
        <img class="section-icon" src="{% static 'assets/icons/courses.png' %}" alt="Icono de cursos"/>
        <span class="text-separator px-1">{{text}}</span>
        <div class="horizontal-separator"></div>
    </div>
</div>

reinicias/courses/templates/components/unitsrow.html
{% load static %}
<div class="accordion-item my-3">
    <h2 class="accordion-header" id="flush-heading{{unit.pk}}">
        <button class="accordion-button collapsed" {% if block %}disabled{% endif %} type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{unit.pk}}" aria-expanded="false" aria-controls="flush-collapse{{unit.pk}}">
            <img class="section-icon {% if not block %}d-none{% endif %}" src="{% static 'assets/icons/block.png' %}" alt="Tema Bloqueado">
            {{unit.title}}
        </button>
    </h2>
    {% if not block %}
    <div id="flush-collapse{{unit.pk}}" class="accordion-collapse collapse course-row-content" aria-labelledby="flush-heading{{unit.pk}}" data-bs-parent="#{{parent_id}}">
        <div class="pt-md-4 pb-md-2 pb-2">
            <div class="w-100">
                <div class="w-100"><strong>Contenido:</strong></div>
                <!-- CONTENIDO -->
                <ul>
                {% for content in contents %}
                    <li class="w-100"><strong class="text-capitalize">{{content}}:&nbsp;</strong><a target="_blank" href="{{MEDIA_URL}}{{content.resource.name}}" rel="noopener">{{content.resource.name}}</a></li>
                {% endfor %}
                </ul>
            </div>
            <div class="w-100 d-flex align-items-center">
                {% if autoev_block %}
                <span class="ms-3 text-danger"><strong>Repasa el temario e int&eacute;ntalo la semana que viene</strong></span>
                {% else %}
                    {% if not unit.completed %}
                    <button class="my-3 courses-button courses-button-cyan">
                        <a class="text-white" href="{% url 'autoevaluation_start' unit.autoevaluation.pk %}" onclick="return confirm('¿Desea comenzar un intento para la autoevaluación?')">Autoevaluaci&oacute;n</a>
                    </button>
                    {% endif %}
                <div class="d-flex flex-column">
                    <span class="ms-3"><strong>Calificaci&oacute;n:&nbsp;</strong>{% if unit.calification is not None %}{{unit.calification}}{% else %}&dash;{% endif %}</span>
                    <span class="ms-3"><strong>Intentos:&nbsp;</strong>{% if unit.tries is not None %}{{unit.tries}}{% else %}&dash;{% endif %}</span>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
</div>

reinicias/courses/templates/components/unitsrow_teachers.html
{% load static %}
<div class="accordion-item my-3">
    <h2 class="accordion-header" id="flush-heading{{unit.pk}}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{unit.pk}}" aria-expanded="false" aria-controls="flush-collapse{{unit.pk}}">
            {{unit.title}}
        </button>
    </h2>
    <div id="flush-collapse{{unit.pk}}" class="accordion-collapse collapse course-row-content" aria-labelledby="flush-heading{{unit.pk}}" data-bs-parent="#{{parent_id}}">
        <div class="pt-md-4 pb-md-2 pb-2 container-fluid">
            <div class="row">
                <div class="col-12 w-100"><strong>Contenido:</strong></div>
                <!-- CONTENIDO -->
                <ul class="col-12">
                {% for content in contents %}
                    <li class="w-100">
                        {% if not published %}
                        <a href="units/{{unit.pk}}/resources/{{content.pk}}/remove" onclick="return confirm('¿Está seguro de querer borrar {{content.get_file_with_extension}}?')" class="bi bi-x-square-fill text-danger"></a>
                        &nbsp;
                        {% endif %}
                        <strong class="text-capitalize">{{content}}:&nbsp;</strong>
                        <a target="_blank" href="{{MEDIA_URL}}{{content.resource.name}}" rel="noopener">{{content.get_file_with_extension}}</a>
                    </li>
                {% endfor %}
                </ul>
            </div>
            <div class="w-100 row align-items-center">
                <div class="col-6 col-sm-4 col-md-3 col-xl-2 d-flex justify-content-center">
                    <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="/courses/autoevaluations/{{unit.autoevaluation.pk}}/" >Ver autoevaluaci&oacute;n</a></button>
                </div>
                {% if not published %}
                <div class="col-6 col-sm-4 col-md-3 col-xl-2 d-flex justify-content-center">
                    <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="units/{{unit.pk}}/edit" >Editar tema</a></button>
                </div>
                <div class="col-6 col-sm-4 col-md-3 col-xl-2 d-flex justify-content-center">
                    <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="units/{{unit.pk}}/delete" onclick="return confirm('¿Está seguro de querer eliminar el tema {{unit.title}}?')">Borrar tema</a></button>
                </div>
                <div class="col-6 col-sm-4 col-md-3 col-xl-2 d-flex justify-content-center">
                    <button class="my-3 courses-button courses-button-cyan"><a class="text-white" href="units/{{unit.pk}}/resources/add/">A&ntilde;adir recurso</a></button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>